# Generated by Django 4.2.7 on 2024-01-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anis', '0003_produk_gambar_empat_produk_gambar_lima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.CharField(max_length=200, null=True)),
                ('nama', models.CharField(max_length=200, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Data Kontak',
            },
        ),
    ]
